version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://github.com/cheehoong/asustor-apk-pihole
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
#    ports:
#      - "53:53/tcp"
#      - "53:53/udp"
#      - "67:67/udp"
#      - "8080:80/udp"
#      - "4443:443/tcp"
    environment:
      TZ: 'Asia/Singapore'
      ServerIP: 192.168.1.1
#      VIRTUAL_HOST: 192.168.1.1
      DNSMASQ_USER : 'root'
      WEB_PORT: '3001'
      WEBPASSWORD: 'admin'
# Volumes store your data between container upgrades
    volumes:
      # - './etc-pihole/:/etc/pihole/'
      # - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - '/share/Docker/pihole-docker/etc-pihole/:/etc/pihole/'
      - '/share/Docker/pihole-docker/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
#    cap_add:
#      - NET_ADMIN
    restart: unless-stopped
